### ISSUE TITLE
Int32 Issues

### ISSUE THREAD

**Issue by brn2swim** [lazear/Libra#2]
Thanks for awesome app.  I did run into some issues lately with order numbers getting too large for the int32 variables.  I changed most to long and that seemed to work.

Also the stop orders are always showing up in the summary box after being placed.  Although they are not showing up they are still firing on time.

**Comment by lazear** [comment]
Can you provide more details about the stop order issues?
________________________________

**Comment by brn2swim** [comment]
Yeah so when i place a stop order it does not show up under pending. However if i place another order after the stop order it will show up in the tree with the plus sign to expend the tree

Thanks

Chad

**Comment by lazear** [comment]
I've rolled out some code - See if this fixes the issue for you.
